name: Build and Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Deploy to GitHub Pages
        run: |
          # Save .git directory
          mv .git ./dist/
          
          # Get all tracked files
          TRACKED_FILES=$(git ls-tree --name-only HEAD | grep -v "dist" | grep -v ".github")
          
          # Remove tracked files except .github directory
          for file in $TRACKED_FILES; do
            rm -rf "$file"
          done
          
          # Move built files to root
          mv dist/* ./
          rmdir dist
          
          # Configure git
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # Add all changes
          git add -A
          
          # Commit changes
          git commit -m "Deploy: $(date)" || echo "No changes to commit"
          
          # Push changes
          git push origin main 